@Echo OFF
CLS
IF NOT EXIST SettingsRE.txt EXIT 1

ECHO ==============================================
ECHO Loading Settings
ECHO ==============================================
FOR /F "delims=; tokens=1" %%I in (SettingsRE.txt) DO SET %%I


ECHO ==================================
ECHO Mounting Drive
ECHO ==================================
ECHO SELECT DISK %DISKID% >"%TMP%\Hdd.txt"
ECHO SELECT PARTITION %RECOVERYPART% >>"%TMP%\Hdd.txt"
ECHO ASSIGN LETTER=%RECOVERYLETTER% >>"%TMP%\Hdd.txt"
DISKPART /S "%TMP%\Hdd.txt"


IF NOT EXIST %RECOVERYLETTER%:\Recovery\WindowsRE\Install.Wim EXIT 0
IF "%RECOVERYLETTER%"=="A" EXIT 1
IF "%RECOVERYLETTER%"=="B" EXIT 2
IF "%RECOVERYLETTER%"=="C" EXIT 3
IF "%RECOVERYLETTER%"=="D" EXIT 4
IF "%RECOVERYLETTER%"=="E" EXIT 5
IF "%RECOVERYLETTER%"=="F" EXIT 6
IF "%RECOVERYLETTER%"=="G" EXIT 7
IF "%RECOVERYLETTER%"=="H" EXIT 8
IF "%RECOVERYLETTER%"=="I" EXIT 9
IF "%RECOVERYLETTER%"=="J" EXIT 10
IF "%RECOVERYLETTER%"=="K" EXIT 11
IF "%RECOVERYLETTER%"=="L" EXIT 12
IF "%RECOVERYLETTER%"=="M" EXIT 13
IF "%RECOVERYLETTER%"=="N" EXIT 14
IF "%RECOVERYLETTER%"=="O" EXIT 15
IF "%RECOVERYLETTER%"=="P" EXIT 16
IF "%RECOVERYLETTER%"=="Q" EXIT 17
IF "%RECOVERYLETTER%"=="R" EXIT 18
IF "%RECOVERYLETTER%"=="S" EXIT 19
IF "%RECOVERYLETTER%"=="T" EXIT 20
IF "%RECOVERYLETTER%"=="U" EXIT 21
IF "%RECOVERYLETTER%"=="V" EXIT 22
IF "%RECOVERYLETTER%"=="W" EXIT 23
IF "%RECOVERYLETTER%"=="X" EXIT 24
IF "%RECOVERYLETTER%"=="Y" EXIT 25
IF "%RECOVERYLETTER%"=="Z" EXIT 26
IF "%RECOVERYLETTER%"=="a" EXIT 1
IF "%RECOVERYLETTER%"=="b" EXIT 2
IF "%RECOVERYLETTER%"=="c" EXIT 3
IF "%RECOVERYLETTER%"=="d" EXIT 4
IF "%RECOVERYLETTER%"=="e" EXIT 5
IF "%RECOVERYLETTER%"=="f" EXIT 6
IF "%RECOVERYLETTER%"=="g" EXIT 7
IF "%RECOVERYLETTER%"=="h" EXIT 8
IF "%RECOVERYLETTER%"=="i" EXIT 9
IF "%RECOVERYLETTER%"=="j" EXIT 10
IF "%RECOVERYLETTER%"=="k" EXIT 11
IF "%RECOVERYLETTER%"=="l" EXIT 12
IF "%RECOVERYLETTER%"=="m" EXIT 13
IF "%RECOVERYLETTER%"=="n" EXIT 14
IF "%RECOVERYLETTER%"=="o" EXIT 15
IF "%RECOVERYLETTER%"=="p" EXIT 16
IF "%RECOVERYLETTER%"=="q" EXIT 17
IF "%RECOVERYLETTER%"=="r" EXIT 18
IF "%RECOVERYLETTER%"=="s" EXIT 19
IF "%RECOVERYLETTER%"=="t" EXIT 20
IF "%RECOVERYLETTER%"=="u" EXIT 21
IF "%RECOVERYLETTER%"=="v" EXIT 22
IF "%RECOVERYLETTER%"=="w" EXIT 23
IF "%RECOVERYLETTER%"=="x" EXIT 24
IF "%RECOVERYLETTER%"=="y" EXIT 25
IF "%RECOVERYLETTER%"=="z" EXIT 26

EXIT 0